package config

import (
	"reflect"
	"strings"
)

// The .env.example in the repository root is generated from this package: the
// names, defaults and required-ness of the Config struct, and the `desc`
// sentence each field carries. That sentence is written once, here, and nowhere
// else - which is the point. Run `make env-example` after touching a field;
// TestEnvExampleGenerated fails when the file in the repository and the tags
// have drifted apart.
//
// What a variable is for, in Russian and for the person reading the admin
// configuration page, is product copy and lives with the rest of it in
// web/src/pages/configText.ts. Two audiences, two texts, each written in one
// place - and a test on both sides so neither can quietly lose a variable.

// commentWidth is where a comment line wraps, "# " included.
const commentWidth = 79

const envExampleHeader = `Generated from internal/config: run "make env-example" after changing a
variable, and do not edit this file by hand.

Copy it to .env and adjust. Uncommented lines carry the value this example
recommends; commented ones are optional, or only needed in a particular mode.

The portal always talks to the real Harbor, GitLab and Argo CD and refuses to
start without their addresses and tokens. The in-memory fakes next to each
client are used by tests only and cannot be switched on from here.`

// RenderEnvExample builds the contents of the root .env.example: a section per
// configuration group, in the order the groups are declared, and inside it the
// variables in the order the Config struct declares them. Every variable is a
// block of its own - what it is for, then the line to edit - and the blocks are
// set apart by a blank line, because a wall of comments and assignments is read
// by nobody.
func RenderEnvExample() string {
	rule := "# " + strings.Repeat("=", commentWidth-2)
	blocks := []string{strings.Join(comment(envExampleHeader), "\n")}
	fields := envFields()
	for _, g := range groups {
		in := fields[g.name]
		if len(in) == 0 {
			continue
		}
		head := []string{rule, "# " + g.title, rule}
		head = append(head, comment(g.intro)...)
		blocks = append(blocks, strings.Join(head, "\n"))
		for _, f := range in {
			block := append(comment(f.doc), f.assignment())
			blocks = append(blocks, strings.Join(block, "\n"))
		}
	}
	return strings.Join(blocks, "\n\n") + "\n"
}

// envField is one variable as the example writes it.
type envField struct {
	name      string
	doc       string
	value     string // default, or the example when there is no default
	commented bool   // shown as a suggestion rather than a setting
}

func (f envField) assignment() string {
	if f.commented {
		return "# " + f.name + "=" + f.value
	}
	return f.name + "=" + f.value
}

// envFields reads the Config struct and returns its variables by group, each
// group in struct order. A variable is written out uncommented when it has a
// default or is required (the example then ships a working local value), and
// commented when it is optional - with a sample value where the tag gives one.
func envFields() map[string][]envField {
	out := map[string][]envField{}
	rt := reflect.TypeFor[Config]()
	for i := range rt.NumField() {
		ft := rt.Field(i)
		name, required := envKey(ft.Tag.Get("env"))
		if name == "" {
			continue
		}
		def, example := ft.Tag.Get("envDefault"), ft.Tag.Get("example")
		f := envField{name: name, doc: withOptions(name, ft.Tag.Get("desc"))}
		switch {
		case def != "":
			f.value = def
		case required:
			// Written out as a setting rather than a suggestion, and said out
			// loud: this is the line the reader has to fill in.
			f.value, f.doc = example, strings.TrimSpace(f.doc)+" Required."
		default:
			f.value, f.commented = example, true
		}
		group := groupOf(name)
		out[group] = append(out[group], f)
	}
	return out
}

// withOptions appends the values a variable accepts to its description. The
// description says what the variable is for, in prose; the list says what may be
// typed on the line below, and it is spelled out rather than left to the reader
// to guess from the default. Same list the configuration page shows, from
// describe.go, so it is written down once.
func withOptions(name, doc string) string {
	accepted := options[name]
	if len(accepted) == 0 {
		return doc
	}
	return strings.TrimSpace(doc) + " Possible values: " + strings.Join(accepted, ", ") + "."
}

// comment turns prose into comment lines: paragraphs separated by a bare "#",
// each wrapped to commentWidth. Text with no words at all yields nothing, so a
// field without a doc tag simply has no comment above it (the test that every
// field carries one is what makes sure that never happens).
func comment(text string) []string {
	var out []string
	for para := range strings.SplitSeq(text, "\n\n") {
		if len(out) > 0 {
			out = append(out, "#")
		}
		out = append(out, wrap(strings.Join(strings.Fields(para), " "), commentWidth-2)...)
	}
	return out
}

func wrap(text string, width int) []string {
	var out []string
	line := ""
	for _, word := range strings.Fields(text) {
		switch {
		case line == "":
			line = word
		case len(line)+1+len(word) <= width:
			line += " " + word
		default:
			out = append(out, "# "+line)
			line = word
		}
	}
	if line != "" {
		out = append(out, "# "+line)
	}
	return out
}
